- name: Restart systemd-resolved
  become: true
  systemd_service:
    name: systemd-resolved
    state: restarted
  listen: restart systemd-resolved

- name: Restart docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ pihole_install_path }}"
    state: present
    remove_orphans: true
    wait: true
    recreate: always
  listen: restart docker compose
