- name: Upgrade all packages to latest
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    lock_timeout: 600
  become: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - htop
      - neovim
      - gnupg
      - ca-certificates
      - curl
    state: latest
    lock_timeout: 600
  become: true
