- name: Restart docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ authentik_install_path }}"
    state: present
    remove_orphans: true
    wait: true
    recreate: always
  listen: restart docker compose
