- name: Configure adguard instance
  hosts: adguard
  roles:
    - common
    - docker
    # - pihole
    - adguard
  tags:
    - adguard

- name: Configure vault instance
  hosts: vault
  roles:
    - common
    - docker
    - stirlingpdf

- name: Configure private edge
  hosts: edge
  roles:
    - common
    - caddy
  vars:
    type: private
  tags:
    - caddy

- name: Configure public edge
  hosts: public-edge
  roles:
    - common
    - caddy
  vars:
    type: public
  tags:
    - caddy

- name: Configure auth instance
  hosts: auth
  roles:
    - common
    - docker
    - authentik
  tags:
    - authentik
