- name: Configure pihole instance
  hosts: pihole
  roles:
    - common
    - docker
    - pihole

- name: Configure vault instance
  hosts: vault
  roles:
    - common
    - docker
    - stirlingpdf
