- name: Configure adguard instance
  hosts: adguard
  roles:
    - common
    - docker
    # - pihole
    - adguard
  tags:
    - adguard

- name: Configure vault instance
  hosts: vault
  roles:
    - common
    - docker
    - stirlingpdf

- name: Configure edge instance
  hosts: edge
  roles:
    - common
    - caddy
  tags:
    - caddy
