- name: Add postgresql GPG key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: Add postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bookworm-pgdg main
    state: present
    filename: "pgdg"
  become: true

- name: Install postgresql
  apt:
    pkg:
      - postgresql-16
      - python3-psycopg2
    state: latest
  become: true

- name: Include primary tasks
  include_tasks: primary.yaml
  when: postgresql_role == 'primary'

- name: Include replica tasks
  include_tasks: replica.yaml
  when: postgresql_role == 'replica'
