- name: Copy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
    mode: "0644"
    owner: postgres
    group: postgres
  become: true

- name: Allow local connections
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    users: all
    databases: all
    method: scram-sha-256
    source: 10.88.111.0/24
  become: true

- name: Debug password
  debug:
    msg: "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/core/postgres/credentials/replicator:password') }}"

- name: Create replicator user
  community.postgresql.postgresql_user:
    name: replicator
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/core/postgres/credentials/replicator:password') }}"
    role_attr_flags: REPLICATION
  become: true
  become_user: postgres

- name: Allow replicator connections
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    users: replicator
    databases: replication
    method: scram-sha-256
    source: 10.88.111.0/24
  become: true

- name: Create terraform user
  community.postgresql.postgresql_user:
    name: terraform
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'kv/data/core/postgres/credentials/terraform:password') }}"
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres

- name: Restart postgresql
  become: true
  ansible.builtin.systemd_service:
    enabled: true
    state: restarted
    name: postgresql@16-main
